plugins {
    id "com.android.application"
}

android {
    namespace "com.movieroom.web"
    compileSdk 35

    defaultConfig {
        applicationId "com.movieroom.web"
        minSdk 23
        targetSdk 35
        versionCode 11
        versionName "1.0.10"
        buildConfigField "String", "MOVIE_ROOM_BASE_URL", '"https://movie-downloads-six.vercel.app"'
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
